spring:
  profile: local
  datasource:
    url: jdbc:postgresql://localhost:6000/db_local
    username: user_local
    password: pass_local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false # property to avoid clob warning
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect # property to avoid clob warning
redis:
  host: localhost
  port: 6379
  pass:
---

spring:
  profiles: container
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  pass: ${REDIS_PASS}
